const BACKEND_URL = process.env.REACT_APP_BACKEND_URL
const PAGINATION_ITEMS = process.env.REACT_APP_PAGINATION_ITEMS
const CREDENTIALS_STORE_KEY  = process.env.REACT_APP_CREDENTIALS_STORE_KEY
export { BACKEND_URL, PAGINATION_ITEMS, CREDENTIALS_STORE_KEY }